[package]
name = "comment-server"
version = "0.1.0"
authors = ["Jonathan Fok kan <jfokkan@gmail.com>"]

[dependencies]
ws = "0.5.3"
slog = "1.0.0"
slog-term = "1.1.0"
slog-scope = "0.2.0"
slog-envlogger = "0.5.0"